spring.application.name=market-research-mcp-server
spring.ai.openai.api-key=${OPENAI_API_KEY}
server.port=8081
twelve.data.api-key=${TWELVE_DATA_API_KEY}
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=market-server
spring.ai.mcp.server.version=1.0.0