spring.application.name=client
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.mcp.client.streamable-http.connections.market-server.url=http://localhost:8081
#spring.main.web-application-type=servlet
spring.ai.mcp.client.request-timeout=120s
spring.ai.ollama.init.timeout=120s

